### ISSUE TITLE
CTRL+Backspace is already assigned on VSCode for Windows

### ISSUE THREAD

**Issue by bob-v-t** [plievone/vscode-template-literal-editor#1]
Hi @plievone,

Thanks again for making this extension and for your work on the coffeescript support. I love it.
There is a small thing that I would like to see done differently though: On WindowsVSCode the CTRL+Backspace is assigned to `deleteWordLeft`.

This is the default keybinding in many editors on Windows and Linux.
Is there something we can do to work around this? Maybe make it a setting? Or make it dependent on the platform? (CTRL+W already seems to do the job on VSCode for Windows)

**Comment by plievone** [comment]
Hi, yes, let's fix that. I guess keybindings can be changed in the editor too, but it's better if the defaults work ok. Ctrl+Backspace is not needed so much anymore, as Ctrl+W seems to work now, and personally I just use Ctrl+Enter in the literal editor to keep the cursor position. We could remove the offending keybinding and just use "Close All Subdocuments" action directly, but let's just demote it to Ctrl+Shift+Backspace for now, that should be available. I'll release a patch update soon!

**Comment by bob-v-t** [comment]
Wow, that was quick. Good solution!

Thanks a lot!
