### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by comerc** [plievone/vscode-template-literal-editor#2]
Please add support for [PostCSS](https://github.com/MhMadHamster/vscode-postcss-language).

**Comment by comerc** [comment]
[PostCSS syntax](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS) added for this.

**Comment by plievone** [comment]
Hi! I will experiment with it. My initial thought is that postcss support should already be working - it should be in the language selection list when postcss extension is active? But I will check it out, thanks.

**Comment by comerc** [comment]
Sorry, it is works fine. Thank you very match!
