### ISSUE TITLE
Ctrl + Enter does not work in an HTML File

### ISSUE THREAD

**Issue by benjieCodes** [plievone/vscode-template-literal-editor#4]

**Comment by plievone** [comment]
Hi, you can add the following line to your vscode user settings:
```json
"templateLiteralEditor.regexes.html": "(`)([\\s\\S]*?)(`)",
```
It complains about an unknown configuration setting, but works ok. I might release a new version with the regexp included, thanks for noticing.

**Comment by benjieCodes** [comment]
Works perfect. Thank you for the quick fix!
